/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface FaceLocation {
  left: number
  top: number
  right: number
  bottom: number
}
export function faceLocations(input: Buffer): Array<FaceLocation>
