/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Location {
  left: number
  top: number
  right: number
  bottom: number
}
export interface Point {
  x: number
  y: number
}
export function compareFaces(one: Array<number>, two: Array<number>): number
export type JsFacial = Facial
export class Facial {
  static fromImage(input: Buffer): JsFacial
  locations(): Array<Location>
  landmarks(locations: Array<Location>): Array<Array<Point>>
  encodings(location: Location, jitters?: number | undefined | null): Array<number>
}
